### ISSUE TITLE
Unreadable Notebook: /home/zly/code/Multi-omics/momix-notebook/scripts/Comparison_in_cancer.ipynb FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by zhenglinyi** [ComputationalSystemsBiology/momix-notebook#3]
Unreadable Notebook: /home/zly/code/Multi-omics/momix-notebook/scripts/Comparison_in_cancer.ipynb FileNotFoundError(2, 'No such file or directory')

**Comment by tuhulab** [comment]
Could you check whether this file (Comparison_in_cancer.ipynb) exists, or whether you have the right permission to read this file?

**Comment by lcan88** [comment]
How are you getting that error? Did you follow the procedure in the readme from conda environment installation to jupiter notebook running?

**Comment by chernan** [comment]
Without a follow up, closing the issue.
