### ISSUE TITLE
MOFA error

### ISSUE THREAD

**Issue by tuhulab** [ComputationalSystemsBiology/momix-notebook#5]
When I run **momix-notebook/scripts/Comparison in simulated data.ipynb**,  ## Running the comparisons. I got the error message as shown below. Could the error be related to [depreciated MOFA v1]( https://www.rdocumentation.org/packages/MOFA/versions/1.3.1)?
 

> Warning message in createMOFAobject(omics):
> “View names are not specified in the data, renaming them to: view_1, view_2, view_3
> ”
> Creating MOFA object from list of matrices,
>  please make sure that samples are columns and features are rows...
> 
> 
> Checking data options...
> 
> Checking training options...
> 
> Checking model options...
> 
> [1] "No output file provided, using a temporary file..."
> Error in py_module_import(module, convert = convert): ModuleNotFoundError: No module named 'mofa'
> Traceback:
> 
> 1. runfactorization(simul_folder, paste0("omics", 1:3, ".txt"), 
>  .     num.clusters, sep = "\t", filtering = "none")
> 2. runMOFA(MOFAobject)
> 3. import("mofa")
> 4. py_module_import(module, convert = convert)

**Comment by lcan88** [comment]
It should not be connected to that, we created the conda package and no modification has been done on that. The system cannot find the MOFA library. Did you first install the conda environment and run the notebook with the environment activated?

**Comment by tuhulab** [comment]
![Screenshot 2021-02-16 at 13 18 38](https://user-images.githubusercontent.com/45359616/108062093-976f8300-7059-11eb-96e6-818153218b49.png)

Yes, I've been following all the procedures. Strangely, I can see mofa in my conda environment.

**Comment by lcan88** [comment]
ok!  MOFA cannot find the correct python version. You should add in the beginning of the runfactorization.R file the following two lines:

library(reticulate)
use_python("path to miconda3/miniconda3/envs/momix/bin/python3.6", required=TRUE)

**Comment by tuhulab** [comment]
Thx, @lcan88 . It's working perfectly now!
